### ISSUE TITLE
How should it be implemented to Freeform?

### ISSUE THREAD

**Issue by tudorradubarbu** [digitalpulsebe/craft-friendly-captcha#1]
Hello guys and thank you for the plugin.

As most of the Craft websites use Freeform, what is a good way to implement this with Freeform?
But first of all, does it work with Freeform?

**Comment by jodeba** [comment]
Hi,

thank you for your message. I did not find a way to have an out-of-box integration with Freeform. You can however register to the [Freeform submission events](https://docs.solspace.com/craft/freeform/v3/developer/submission-events.html) in your own custom module.
Formie allows for custom integrations to be registered, but unfortunately Freeform does not.

I hope this helps.
