### ISSUE TITLE
Setting to EU endpoint fails

### ISSUE THREAD

**Issue by tudorradubarbu** [digitalpulsebe/craft-friendly-captcha#2]
Hello.

When I set the endpoint to use the EU, it crashes with:

`Getting unknown property: digitalpulsebe\friendlycaptcha\services\ValidateService::endpoint
`

I think because of this:

`$defaultAttributes['data-puzzle-endpoint'] = FriendlyCaptcha::$plugin->validate->getEndpointUrl($this->endpoint, 'puzzle')
`

`$this->endpoint `should be `$settings->endpoint`

Is this ok?

**Comment by jodeba** [comment]
Hi, 

Thank you for reporting, you're right!
This is now fixed in [2.0.5](https://github.com/digitalpulsebe/craft-friendly-captcha/releases/tag/2.0.5) and [1.0.4](https://github.com/digitalpulsebe/craft-friendly-captcha/releases/tag/1.0.4)
