### ISSUE TITLE
[FR] Integration of own server endpoint and assets

### ISSUE THREAD

**Issue by ammannbe** [digitalpulsebe/craft-friendly-captcha#3]
Hi there,

I have a feature request: I'd like to be able to add a custom endpoint, or even integrate the [lite-server](https://github.com/FriendlyCaptcha/friendly-lite-server) into the plugin. So we are independent from the friendly captcha's servers.

Also it would be really nice, if this plugin would bring its own javascript files, instead of using the [unpkg.com](https://github.com/digitalpulsebe/craft-friendly-captcha/blob/b21eeafb3334688e758bf058b0cd689e7523c69d/src/services/ValidateService.php#L148) version.

**Comment by jodeba** [comment]
Hi! Thank you for your suggestions, sounds very reasonable. I'll be looking in to it soon!👍

**Comment by jodeba** [comment]
Hi @ammannbe, you can access these features in release [2.1.0](https://github.com/digitalpulsebe/craft-friendly-captcha/releases/tag/2.1.0) or [1.1.0](https://github.com/digitalpulsebe/craft-friendly-captcha/releases/tag/1.1.0) for Craft 3
